#!/usr/bin/env bash
# Description: This script transfers a file from a client to a server using SCP.

# Check if all required arguments are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Transfer the file using SCP
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~

