#!/usr/bin/env bash
# This script configures a new Ubuntu machine to add a custom HTTP response header in Nginx

# Update package lists and install Nginx
apt-get -y update
apt-get -y install nginx

# Add a custom response header to identify the server for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Restart nginx to apply changes
service nginx restart

