#!/usr/bin/env bash
# This script restores the default server port for Nginx.

# Create a symbolic link to enable the default Nginx configuration.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start the Nginx service.
sudo service nginx start

