#!/usr/bin/env bash
# Script to restore default Nginx configuration

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -s reload
nginx -s stop >/dev/null 2>&1 || echo "nginx is not running"

