#!/usr/bin/env bash
# Counter variable
counter=1
# Loop using while
while [ $counter -le 10 ]; do
    # Check if it's the 9th iteration
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    # Increment counter
    ((counter++))
done

