#!/usr/bin/env bash
# Initialize counter
counter=1
# Loop from 1 to 10
while [ $counter -le 10 ]; do
    # Check conditions for each iteration
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    
    # Increment counter
    counter=$((counter + 1))
done

