#!/bin/bash

# Check if the script is running in Docker
if [ -f "/.dockerenv" ]; then
    # Add entries to /etc/hosts
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

    echo "Hosts file configured successfully."
else
    echo "This script should be run inside a Docker container."
fi

