#!/usr/bin/env bash

# Script to reconfigure a broken container to work with Nginx on port 8080

# Stop any Apache2 instances running on port 8080
service apache2 stop
pkill apache2

# Configure Nginx to listen on port 8080
CONFIG_LOCATION='/etc/nginx/sites-available/default'
CONFIG="
server {
	listen 8080 default_server;
	listen [::]:8080 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}
}"
printf "%s" "$CONFIG" > "$CONFIG_LOCATION"

# Set proper ownership and permissions for the Nginx configuration file
chown nginx "$CONFIG_LOCATION"
chmod 644 "$CONFIG_LOCATION"

# Restart Nginx as the nginx user
sudo -u nginx service nginx restart

