#!/usr/bin/env bash
# Script to configure Nginx to run as the nginx user and listen on port 8080

# Stop any Apache2 instances running on port 8080
service apache2 stop
pkill apache2

# Configure Nginx to run as the nginx user and listen on port 8080
CONFIG_LOCATION='/etc/nginx/nginx.conf'
CONFIG="
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    ##
    # Basic Settings
    ##

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # Logging Settings
    ##

    access_log /var/log/nginx/access.log;

    ##
    # Gzip Settings
    ##

    gzip on;

    ##
    # Virtual Host Configs
    ##

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
    server {
        listen 8080;
        listen [::]:8080;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name localhost;

        location / {
            try_files \$uri \$uri/ =404;
        }
    }
}"
printf "%s" "$CONFIG" > "$CONFIG_LOCATION"

# Set proper ownership and permissions for the Nginx configuration file
chown nginx "$CONFIG_LOCATION"
chmod 644 "$CONFIG_LOCATION"

# Restart Nginx as the nginx user
service nginx restart

