#!/bin/bash

# Define variables
key_name="school"
bits=4096
passphrase="betty"

# Create RSA key pair
ssh-keygen -t rsa -b "$bits" -C "$key_name" -f "$key_name" -N "$passphrase"

echo "RSA key pair created successfully."
